// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: kline.proto

package vdsdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//K线
type VDSKLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`       //代码
	Open     float64 `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`         //开盘价
	High     float64 `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`         //最高价
	Low      float64 `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`           //最低价
	Close    float64 `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`       //收盘价
	Preclose float64 `protobuf:"fixed64,8,opt,name=preclose,proto3" json:"preclose,omitempty"` //昨收
	Vol      float64 `protobuf:"fixed64,9,opt,name=vol,proto3" json:"vol,omitempty"`           //成交量
	Amout    float64 `protobuf:"fixed64,10,opt,name=amout,proto3" json:"amout,omitempty"`      //成交额
}

func (x *VDSKLine) Reset() {
	*x = VDSKLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VDSKLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VDSKLine) ProtoMessage() {}

func (x *VDSKLine) ProtoReflect() protoreflect.Message {
	mi := &file_kline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VDSKLine.ProtoReflect.Descriptor instead.
func (*VDSKLine) Descriptor() ([]byte, []int) {
	return file_kline_proto_rawDescGZIP(), []int{0}
}

func (x *VDSKLine) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *VDSKLine) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *VDSKLine) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *VDSKLine) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *VDSKLine) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *VDSKLine) GetPreclose() float64 {
	if x != nil {
		return x.Preclose
	}
	return 0
}

func (x *VDSKLine) GetVol() float64 {
	if x != nil {
		return x.Vol
	}
	return 0
}

func (x *VDSKLine) GetAmout() float64 {
	if x != nil {
		return x.Amout
	}
	return 0
}

var File_kline_proto protoreflect.FileDescriptor

var file_kline_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6b, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6, 0x01,
	0x0a, 0x08, 0x56, 0x44, 0x53, 0x4b, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f,
	0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x72, 0x65, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x6f, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x76, 0x6f, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x6d, 0x6f, 0x75, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x61, 0x6d, 0x6f, 0x75, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x76, 0x64, 0x73,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kline_proto_rawDescOnce sync.Once
	file_kline_proto_rawDescData = file_kline_proto_rawDesc
)

func file_kline_proto_rawDescGZIP() []byte {
	file_kline_proto_rawDescOnce.Do(func() {
		file_kline_proto_rawDescData = protoimpl.X.CompressGZIP(file_kline_proto_rawDescData)
	})
	return file_kline_proto_rawDescData
}

var file_kline_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kline_proto_goTypes = []interface{}{
	(*VDSKLine)(nil), // 0: VDSKLine
}
var file_kline_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kline_proto_init() }
func file_kline_proto_init() {
	if File_kline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VDSKLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kline_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kline_proto_goTypes,
		DependencyIndexes: file_kline_proto_depIdxs,
		MessageInfos:      file_kline_proto_msgTypes,
	}.Build()
	File_kline_proto = out.File
	file_kline_proto_rawDesc = nil
	file_kline_proto_goTypes = nil
	file_kline_proto_depIdxs = nil
}
