---
# viper's GetStringMap function makes key value lowercase
# SIndiNames：the fields for GEP
# SCsvDatafields: given by other code or duplicate from the csv header
default:
    #  Section for virtual account 
    stockinitvalue:  10000.0
    futuresinitvalue:  0.0  
    #  Section for data range, when downloading data from VDS
    begindate:  "2005.01.01T09:35:00.000" 
    enddate:  "2023.02.20T14:35:00.000"
    #  Section for Strategy Targets and info fields
    # SInstrNames:  ["SH600409","SZ000058"]
    # SIndiNames:  ["open","high","low","close","vol","ma5","ma10"]
    # SCsvDatafields:  ["open","high","low","close","vol","amount","ma5","ma10"]
    # 此处为样例标的信息、参与GEP指标信息、全部数据信息
    sinstrnames:  ["sh510010","sh510020","sh510030","sh510060","sh510050","sh510070","sh510090","sh510100","sh510110","sh510120","sh510130","sh510150","sh510160","sh510170","sh510180","sh510190","sh510200","sh510210","sh510220","sh510230"]
    #sinstrnames:  ["sh510030"]
    sindinames: ["Open","Close","High","Low","Volume","Amount","MA3","MA5","Var10"] 
    scsvdatafields:  ["Open","Close","High","Low","Volume","Amount"]
    sadfields:  ["MA3","MA5","Var10"]
    # 期货为空
    finstrnames:  []
    findinames:  [] 
    fcsvdatafields:  []
    fadfields:  []
    # FInstrNames:  ["a1409"]
    # FIndiNames:  ["open","high"]
    # FCsvDatafields:  ["open","high","low","close","vol","amount","openinterest"]
    #  Section for CSV data dir
    #  注意 由于是相对路径 模块测试与main运行略有不同  main ./  test ../
    stockdatadir:  "./tmpdata/stockdata/1min"
    stockdatadirfinal:  "./tmpdata/stockdata/fake/res"
    futuresdatadir:  "./tmpdata/futuresdata/1min"
    futuresdatadirfinal:  "./tmpdata/futuresdata/1min/tmp"
    futuresmtmdatadir:  "./tmpdata/futuresdata/1day"
    #  Section for ContractProp
    confname:  "ContractProp.yaml"
    cpdatadir:  "./config/Manual/"
    #  Section for Matcher parameter
    matcherslippage4s:  0.01
    matcherslippage4f:  1.0
    #  Section for Performance Analytics Parameter
    riskfreerate:  0.00
    patype:  "TA"
    #  Section for Strategy Module Selection
    strategymodule:  "SortBuy"
    smgeptype:  "Genome"
    smname:  "StrategySB"
    smdatadir:  "./config/Manual"       