---
# viper's GetStringMap function makes key value lowercase
# SIndiNames：the fields for GEP
# SCsvDatafields: given by other code or duplicate from the csv header
default:
    #  Section for virtual account 
    stockinitvalue:  100000.0
    futuresinitvalue:  0.0  
    #  Section for data range
    begindate:  "2017/10/9 9:39"
    enddate:  "2017/10/20 15:00"
    #  Section for Strategy Targets and info fields
    # SInstrNames:  ["SH600409","SZ000058"]
    # SIndiNames:  ["open","high","low","close","vol","ma5","ma10"]
    # SCsvDatafields:  ["open","high","low","close","vol","amount","ma5","ma10"]
    # 此处为样例标的信息、参与GEP指标信息、全部数据信息
    sinstrnames:  ["sz002673"]
    sindinames:  ["close","vol","ma1"]
    scsvdatafields:  ["open","high","low","close","vol","amount","change","changerate","amplitude",	"openinterest","ma1","ma2","ma3","ma4"]
    # 期货为空
    finstrnames:  []
    findinames:  [] 
    fcsvdatafields:  []
    # FInstrNames:  ["a1409"]
    # FIndiNames:  ["open","high"]
    # FCsvDatafields:  ["open","high","low","close","vol","amount","openinterest"]
    #  Section for CSV data dir
    #  注意 由于是相对路径 模块测试与main运行略有不同  main ./  test ../
    stockdatadir:  "./tmpdata/stockdata/10min"
    futuresdatadir:  "./tmpdata/futuresdata/1min"
    futuresmtmdatadir:  "./tmpdata/futuresdata/1day"
    #  Section for ContractProp
    confname:  "ContractProp.yaml"
    cpdatadir:  "./config/Manual/"
    #  Section for Matcher parameter
    matcherslippage4s:  0.01
    matcherslippage4f:  1.0
    #  Section for Performance Analytics Parameter
    riskfreerate:  0.00
    patype:  "TA"
    #  Section for Strategy Module Selection
    strategymodule:  "Simple"
    smgeptype:  "Genome"
    smname:  "Strategy"
    smdatadir:  "./config/Manual"       