ii:
    - inditype: MA
      infoslice:
        - Close
      name: MA3
      parslice:
        - 6
    - inditype: Var
      infoslice:
        - Close
      name: Var10
      parslice:
        - 10
