ii:
    - inditype: MA
      infoslice:
        - Close
      name: MA3
      parslice:
        - 3
    - inditype: MA
      infoslice:
        - Close
      name: MA5
      parslice:
        - 5
    - inditype: MA
      infoslice:
        - Close
      name: MA8
      parslice:
        - 8
    - inditype: MA
      infoslice:
        - Close
      name: MA10
      parslice:
        - 10
    - inditype: Var
      infoslice:
        - Close
      name: Var10
      parslice:
        - 10
