contractprop:
    confname: ContractProp.yaml
    cpdatadir: ./config/Manual/
datafields:
    fadfields:
        - MA3
    fcsvdatafields: []
    findinames: []
    finstrnames: []
    sadfields:
        - MA3
    scsvdatafields:
        - Open
        - Close
        - High
        - Low
        - Volume
        - Amount
    sindinames:
        - Open
        - Close
        - High
        - Low
        - Volume
        - MA3
    sinstrnames:
        - sh510050
matcherparam:
    matcherslippage4f: 1
    matcherslippage4s: 0.01
stgmodel:
    smdatadir: ./config/Manual
    smgeptype: Genome
    smname: Strategy
    strategymodule: Simple
va:
    sacct:
        inittime: 2023.01.18T09:35:00.000
        udtime: 2023.01.30T14:10:00.000
        mktval: 99834.48130000001
        fundavail: 48124.48130000001
        allprofit: 0
        allcommission: 5.5187
        posmap:
            sh510050:
                udtime: 2023.01.30T14:10:00.000
                postdys:
                    - udtime: 2023.01.30T14:10:00.000
                      instid: sh510050
                      baseprice: 51.87
                      lastprice: 51.71
                      num: 10
                      equity: 51710
                      scp:
                        contractsize: 100
                        transferfeerate: 1e-05
                        taxrate: 0
                        commbrokerrate: 6.87e-05
                posprevs: []
        marketvalueslice:
            - time: 2023.01.18T09:35:00.000
              mktval: 100000
            - time: 2023.01.18T13:37:00.000
              mktval: 100000
        uuid: 97ad6687-4c4b-4649-b1f2-e39cb5387d59
    facct:
        inittime: 2023.01.18T09:35:00.000
        udtime: 2023.01.18T09:35:00.000
        bmkval: 0
        mktval: 0
        fundavail: 0
        allprofit: 0
        allcommission: 0
        posmap: {}
        marketvalueslice:
            - time: 2023.01.18T09:35:00.000
              mktval: 0
        uuid: 35d5a89e-989f-45f2-bce7-bb24a29042b5
